flask_project/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')
    

flask_project/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_project import db
from flask_project.models import Post
from flask_project.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html', title='New post', form=form, legend='New post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Post update', form=form, legend='Post update')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('posts.allpost'))

flask_project/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_project import db, bcrypt
from flask_project.models import User, Post
from flask_project.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, \
    ResetPasswordForm
from flask_project.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! Now you can log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))
        else:
            flash('Login failed. Please check your email and password', 'attention')
    return render_template('login.html', title='Authentication', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts, user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions on how to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('This is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! Now you can log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset password', form=form)

flask_project/templates/account.html
{% extends "layout/layout.html" %}

{% block content %}
    <div id="content" class="container-fluid flex-column justify-content-center">
      <div class="text-center">
        <img class="rounded-circle img-thumbnail" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group mb-4">
              <legend class="border-bottom mb-4">Account</legend>
              <div class="form-group mb-4">
                  {{ form.username.label(class="form-control-label") }}

                  {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group mb-4">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="input-group mb-3">
                  {{ form.picture.label(class="input-group-text", for="inputGroupFile") }}
                  {{ form.picture(class="form-control", type="file", id="inputGroupFile") }}
                  {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                          <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>      
    </div>
{% endblock content %}

flask_project/templates/allpost.html
{% extends "layout/layout.html" %}

{% block content %}
<div id="content" class="container-fluid">
    {% for post in posts.items %}
    <div class="d-flex mb-4">
        <article class="d-flex flex-column">
            <img class="rounded-circle img-thumbnail" style="margin-right: 10px;"
                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
               style="margin: 0 auto"
               id="author">{{ post.author.username }}</a>
        </article>

        <div class="card w-100" style="margin-bottom: 20px;">
            <div class="card-body">
                <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">
                    {{ post.title }}</a></h4>
                <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                <br>
                <br>
                <p class="card-text">{{ post.content }}</p>
            </div>
        </div>
    </div>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if posts.page == page_num %}
    <a class="btn btn-success mb-4 align-self-start" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num
        }}</a>
    {% else %}
    <a class="btn btn-outline-success mb-4 align-self-start" href="{{ url_for('posts.allpost', page=page_num) }}">
        {{ page_num }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
</div>
{% endblock content %}

flask_project/templates/create_post.html
{% extends "layout/layout.html" %}

{% block content %}
<div id="content" class="container-fluid justify-content-center">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group mb-4">
            <legend class="border-bottom mb-4 text-center">{{ legend }}</legend>
            <div class="form-group mb-4">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group mb-4">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flask_project/templates/index.html
{% extends "layout/layout.html" %}

{% block content %}
<div class="d-flex flex-column justify-content-center">
    <div class="d-flex justify-content-center">
        <h1>WELCOME!</h1>
    </div>
    <hr class="w3-border-grey">
    <br>
    <div class="d-flex justify-content-center flex-wrap">
        <img class="img-fluid mb-2" src="{{ url_for('static', filename='img/blog-template.jpg') }}">
        <p class="d-flex align-items-center text-center w-50">The blog is dedicated to issues and problems in the field of
            programming in python. Please register to access the blog entries if you have not done so before, or go
            through the authorization procedure.
        </p>
    </div>
    <br>
</div>
{% endblock %}

flask_project/templates/login.html
{% extends "layout/layout.html" %}

{% block content %}
    <div id="content" class="container-fluid">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group mb-4">
                <legend class="border-bottom mb-4">Authorization</legend>
                <div class="form-group mb-4">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mb-4">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group mb-4">
                {{ form.submit(class="btn btn-outline-info mr-4") }}
                 <small class="ms-4">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
            <small style="font-size: 15px; font-weight: 500;">
                Needs an account? <a href="{{ url_for('users.register') }}">Register</a>
            </small>
        </form>
    </div>
{% endblock content %}

flask_project/templates/post.html
{% extends "layout/layout.html" %}

{% block content %}
<div class="container d-flex justify-content-center">
    <article class="d-flex flex-column">
        <img class="rounded-circle img-thumbnail" style="margin-right: 10px;"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 0 auto">
            {{ post.author.username }}</a>
    </article>

    <div class="card w-50" style="margin-bottom: 20px;">
        <div class="card-body">
            <h4 class="card-title">{{ post.title }}</h4>
            <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
            <br>
            <br>
            <p class="card-text">{{ post.content }}</p>
        </div>
        <div class="card-footer" style="font-size: 20px;">

            {% if post.author == current_user %}
            <div class="card-footer" style="font-size: 20px;"> {% if post.author == current_user %}<a
                    class="btn btn-secondary btn-sm mt-1 mb-1"
                    href="{{url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
                        data-bs-target="#deleteModal">Delete
                </button>

                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete a post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flask_project/templates/register.html
{% extends "layout/layout.html" %}

{% block content %}
    <div id="content" class="container-fluid">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group mb-4">
                <legend class="border-bottom mb-4">Register</legend>
                <div class="form-group mb-4">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mb-4">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mb-4">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mb-4">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project/templates/reset_request.html
{% extends "layout/layout.html" %}

{% block content %}
    <div id="content" class="container-fluid">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset password</legend>
                <div class="form-group mb-4">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project/templates/reset_token.html
{% extends "layout/layout.html" %}

{% block content %}
    <div id="content" class="container-fluid">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset password</legend>
                <div class="form-group mb-4">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group mb-4">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_project/templates/user_posts.html
{% extends "layout/layout.html" %}

{% block content %}
<div id="content" class="container-fluid">
    <h3 class="mb-3">Posts published by the user {{ user.username }} ({{ posts.total }})</h3>
    {% for post in posts.items %}
    <div class="d-flex mb-4">
        <article>
            <img class="rounded-circle" style="margin-right: 5px;"
                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        </article>

        <div class="card w-100">
            <div class="card-body">
                <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">
                    {{ post.title }}</a></h4>

                <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                <br>
                <br>
                <p class="card-text">{{ post.content }}</p>
            </div>
        </div>
    </div>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if posts.page == page_num %}
    <a class="btn btn-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">
        {{ page_num }}</a>
    {% else %}
    <a class="btn btn-outline-success mb-4"
       href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
</div>
{% endblock content %}